# Generated by Django 3.2.7 on 2021-10-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_experience_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('study', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=50)),
                ('start', models.DateField()),
                ('complete', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
