# Generated by Django 3.2.7 on 2021-10-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20211005_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educ',
            old_name='name',
            new_name='uni_name',
        ),
    ]
